### ISSUE TITLE
DS3231::setMonth using address of PCF8563

### ISSUE THREAD

**Issue by cygnus-x-uno** [cvmanjoo/RTC#11]
setMonth of DS3231.cpp is using the address of the PCF8563 module (instead of DS3231) to transmit the month to the defined register 0x05. See therefore line 396. Fix is easy, simply exchange "PCF8563_ADDR" with DS3231_ADDR".
I have detected the bug during writing a new date "Jun 16 2022" into my DS3231 device. But reading the date I always get month 1 (Jan) back. 
This seems to be the only line where the wrong address is coded.

**Comment by rajeshkanna77** [comment]
@cygnus-x-uno : Thanks for the fix. i too faced the same problem, in June it showed Jan and now in Aug when i set the date, it was set to July month. I was looking for an alternate library to solve the problem. But thank god i saw your post here.
You saved my time. It is working fine after changing the line 396 and restarting IDE.
