### ISSUE TITLE
12 Hour time mode not display 12 hour time

### ISSUE THREAD

**Issue by owieman** [cvmanjoo/RTC#13]
Really scratching my head with this. Constantly displaying 24 hours even though mode is 12 hours.

- Arduino Uno with DS3231 module.
- Tried using `RTC.setHourMode(CLOCK_H12);` in setup - no luck.
- Updated Arduino IDE from 1.8.19 to 2.0.0 and re-compiled - no luck.
- Updated library to 1.6.0 and re-compiled - no luck.
- Power cycled - no luck

Serial monitor output:
```
*** RTC DS3231 ***
Is Clock Running : Yes
Hour Mode :12 Hours
Alarm1 Time : 0:0:0 AM
Alarm1 Tiggered : No
Alarm2 Tiggered : No
INT/SQW Pin Mode : Alarm
Aging Offset : 0
RTC Temperature : 21.25'C

WED 14-2-1922 18:19:25 AM
WED 14-2-1922 18:19:26 AM
WED 14-2-1922 18:19:27 AM
WED 14-2-1922 18:19:28 AM
WED 14-2-1922 18:19:29 AM
WED 14-2-1922 18:19:30 AM
WED 14-2-1922 18:19:31 AM
WED 14-2-1922 18:19:32 AM
```

**Comment by cvmanjoo** [comment]
Looks like time has not been set properly previously.

Set time by using example "Auto_setTime" and check.

Let me know how it goes.

**Comment by ChassaB** [comment]
I am having the same issue. I ran Auto_setTime which worked fine but did not fix the issue.

After RTC.setHourMode(CLOCK_H12); or RTC.setHourMode(CLOCK_H24); I check with Serial.println(myRTC.getHourMode()); which displays 1 or 0 appropriately but when I get the hours hh=myRTC.getHours(); it is always in 24 hour time no matter what mode is set to.

Any thoughts?

**Comment by cvmanjoo** [comment]
Which RTC chip?

First set the Hourmode then set time completely, It should work.

If still it's not working share your code, I will check.

**Comment by ChassaB** [comment]
Thanks for the quick reply. It is a DS3231. I will try that tomorrow.

**Comment by ChassaB** [comment]
OK. That approach worked. Thank you.
Building a "Nixie tubes on a screen" alarm clock/media player for my grandson. It looks like it is better/easier to leave the DS3231 in 24hour mode and code 12 or 24 hour time display. Using ESP32 S3 so I can store a few variables in Flash.

Thanks again

**Comment by cvmanjoo** [comment]
I'm glad it worked, if you encounter any other issue feel free to open new issue.
