### ISSUE TITLE
v1.9.0 - DS3231 Display.begin() throws error

### ISSUE THREAD

**Issue by rich21044** [cvmanjoo/RTC#24]
Upgraded from 1.8.0 to 1.9.0 but compiler (Arduino IDE v2.3.4) flags following error 

Compilation error: 'class DS3231' has no member named 'begin'

error is also present in the included DS3231 example file

Reversion to 1.8.0 fixes the issue.

**Comment by cvmanjoo** [comment]
Fixed this is 1.9.1, You will get update shortly on your Arduino IDE.

**Comment by rich21044** [comment]
Thanks for sorting this out so quickly
