### ISSUE TITLE
24 hr display incorrect.

### ISSUE THREAD

**Issue by TheGermanUSA** [cvmanjoo/RTC#6]
Time is 4:07 pm and should be 16:07 in 24 hr format, but is showing 00:07 instead.

**Comment by cvmanjoo** [comment]
Can u brief me on which RTC and function ?

**Comment by TheGermanUSA** [comment]
It is the DS3231 module here: https://www.amazon.com/gp/product/B00LX3V7F0

Function is the display of time
setHourMode(CLOCK_H24) to set the 24 hour
getHours() then should return the hour value in 24 hr format. At 4 pm, it
should return 16, but returns 00.

Tom

**Comment by cvmanjoo** [comment]
This has been fixed if still has have issue.
Please post the code.
