### ISSUE TITLE
How to use setEpoch()?

### ISSUE THREAD

**Issue by hzc1111** [cvmanjoo/RTC#8]
I found this function from "DS3231.CPP". It is said on the wiki that it can update the Unix timestamp to the time of the chip. Regarding the three parameters in the function, I can only understand the first one-Unix timestamp, but I don't understand the other two. I tried to assign them to 0, but the result is very different from the actual time, so can anyone tell me how to use this function?
![QQ截图20210310183058](https://user-images.githubusercontent.com/48748031/110617500-be405580-81d0-11eb-84c3-5cdec5d03313.png)

**Comment by cvmanjoo** [comment]
Hey, 
This has been fixed also added example,

Let me know, if this still doesn't work,

Thanks
Manjunath
